### PR TITLE
bumped sops up to version 3.9.0 to support EKS pod identities

### PR DESCRIPTION
**Pull request by ryanrf**
Hi @carlpett,

Thank you for creating this provider. I'm trying to run sops in an EKS pod using EKS pod identities, which use a slightly different endpoint for AWS authentication. Sops 3.9.0 is using the [newer AWS go SDK that supports pod identities](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html), so I'm trying to upgrade this provider to support it.
I updated the sops go module (to version 3.9.0)  and ran the tests, which all passed. Please let me know if there is anything I'm missing or anything you'd like me to test on my end.
Thanks in advance!

### CODE REVIEW

**Comment by rkubik-hostersi** [comment]
+1 to merge this PR.
@ryanrf have you find the workaround for now?

**Comment by rkubik-hostersi** [comment]
@carlpett Any chance to merge this one?

**Comment by ryanrf** [comment]
> +1 to merge this PR. @ryanrf have you find the workaround for now?

@rkubik-hostersi yes. We use terragrunt, so I took advantage of the [`run_cmd` command](https://terragrunt.gruntwork.io/docs/reference/built-in-functions/#run_cmd) to run the sops binary directly to decrypt values, then I pass those values into as (sensitive) inputs with terragrunt.

**Comment by Hostersi** [comment]
@ryanrf We had to workaound this in another way (no terragrunt), so you can use my forked provider: https://registry.terraform.io/providers/Hostersi/sops/latest
I hope this PR will be merged to make the original provider working ;)

**Review by carlpett — APPROVED** [review]
Hi @ryanrf,
Thanks for the PR! And apologies for the very slow response, I'm on parental leave and thus have a bit short on time. This all looks good, merging and releasing!

**Pull request merged**
