### PR TITLE
Test and release using GitHub Actions

### PR DESCRIPTION
**Pull request by multani**
This replaces the Circle CI configuration by GitHub Actions.

I think 2 secrets are missing:

* The secrets for the [`hub` command to work during the release phase](https://github.com/carlpett/terraform-provider-sops/blob/375a6b4b9fcd9acd08e47ec8450aa76abf58d84d/GNUmakefile#L46).
* The `DOCKER_HUB_TRIGGER_TOKEN` secret, used during the release phase also.

There's a sample build that fails (due to the missing tokens) in https://github.com/multani/terraform-provider-sops2/runs/6385384905

### CODE REVIEW

**Comment by carlpett** [comment]
Thanks a lot! I think we could actually just skip the docker image. It was mainly useful in some niche cases before the registry came about, and I don't think it is worth supporting any more.

For `hub`, I think the default GITHUB_TOKEN should be sufficient?
```yaml
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by multani** [comment]
> Thanks a lot! I think we could actually just skip the docker image. It was mainly useful in some niche cases before the registry came about, and I don't think it is worth supporting any more.

I was wondering if it was still useful too :) It's gone then :wave: 

> For `hub`, I think the default GITHUB_TOKEN should be sufficient?
> 
> ```yaml
>   env:
>     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```

Yep, that should work :rocket: I'm testing this with a [dummy release](https://github.com/multani/terraform-provider-sops2/releases/tag/v0.0.42) on a dedicated fork in https://github.com/multani/terraform-provider-sops2/actions/runs/2311940226: it seems to work better although I still have some weird timeout issues.

**Comment by carlpett** [comment]
Huh, yeah, that's odd. Not super large binaries either? One option would be to start using `gh` instead, but now we're starting to add a lot of changes at once :sweat_smile:

**Comment by carlpett** [comment]
Hm, that seems like a much larger step. Perhaps we can live with the occasional timeout for now (I assume it's sufficient to just re-run?) and do that as a separate change?

**Comment by multani** [comment]
I'll keep testing because it never went completely through during all my previous tries, I'll let you know if I find something :(

**Comment by multani** [comment]
@carlpett I somehow managed to make it work, I'm not 100% convinced it will be fully reliably though, but in https://github.com/carlpett/terraform-provider-sops/pull/87/commits/0dc12fa61737f1ab9ed6235f3dbd9a292c588835:

* I added a missing configuration to grant write access to the GitHub Actions
* Manually downloading the `hub` CLI tool is not needed as it's provided on the GitHub Actions worker by default (cf. https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md#cli-tools)

You can see it working here: https://github.com/multani/terraform-provider-sops2/runs/6424679171

**Comment by carlpett** [comment]
Yup, those two are present in the current CircleCI implementation as well.
Then let's merge this, thank a lot!

**Pull request merged**
