### PR TITLE
Raw output attribute

### PR DESCRIPTION
**Pull request by nhuray**
Hi @carlpett 

First of all, thanks to bring that provider to the community. 

SOPS is a great tool to improve the developer experience for managing secrets but that Terraform plugin allows to automate the decryption of the secrets in a CI/CD pipeline... so kudos 🥇 

Nevertheless, it seems with the current implementation it's not possible to use the `raw` output attribute when the `input_type` is YAML or JSON due to the logic in `read_data.go`

So in this PR I remove the condition on the `format` and always create the `raw` output attribute.

The `data` output attribute is just created when the format is YAML or JSON (map serialized)

Nicolas

Note: For an unknown reason it seems I had to change the checksums in `go.sum` for `terraform` and `go-getter` libraries

### CODE REVIEW

**Comment by carlpett** [comment]
Hi @nhuray,
Thanks for this PR and the kind words :) 
Could you explain the usecase a bit? Do you need to both access the unmarshalled data *and* the raw data at the same time?

**Comment by Claywd** [comment]
Use case is that when someone wants to encrypt a json or yaml file as a string or "raw" input, your logic always returns a map. I was literally about to fix this myself tonight because in order to encrypt on json file full of credentials I needed a string returned to my provider, which your current implementation is incapable of doing.

**Comment by carlpett** [comment]
Sorry for the lack of movement here, been away on vacation without internet access for a while :palm_tree: 
@Claywd In that usecase, wouldn't you just set `input_type = "raw"`? I'm not against the change, just want to avoid multiple ways to achieve the same thing.

**Comment by HemantNegi** [comment]
@carlpett I am also in favour of this change. The same usecase as @Claywd mentioned, happened with us. The problem with setting `input_type = "raw"` is that it will decode only the files encoded as raw. Which makes them unreadable/gibberish if it's a Json or Yaml file.

**Comment by carlpett** [comment]
@HemantNegi Ok, so your usecase is accessing *both* the raw string *and* the map, in different resources?

**Comment by HemantNegi** [comment]
@carlpett Yes, using both raw and map in different resources can be a use case. But in my case I want to keep the secrets in a .yaml file but want to store/use it in other resource as raw/text format. 
eg. below I want to store the contents of that yaml in a Vault secret (that needs to in text format), so I can use `raw` here. But to use `raw` here I have to encode my .yaml as ` raw` which I want to avoid.
```
resource "vault_generic_secret" "bintray_master_dockerconfig" {
  provider = "vault.cell"
  path     = "some/vault/path"
  data_json = <<EOT
{
  "mysectets.yaml": "${data.sops_file.bintray_dockerconfig.raw}"
}
EOT
}
```

**Comment by abhisheksinghrathod** [comment]
Hi @carlpett ,
I am also looking for a feature very very similar to this thread.
My use case is to store the [CoreOS Alertmanager](https://coreos.com/operators/prometheus/docs/latest/user-guides/alerting.html) configuration file as a secret in [Hashicorp Vault](https://www.vaultproject.io/) using [Hashicorp Terraform](https://www.terraform.io/).
Alertmanager config file is a yaml file which contains integration for PD/Slack etc for routing alerts and it mounts this file as secret -- More about alertmanager secret config file [here](https://prometheus.io/docs/alerting/configuration/).
I can upload the config file to the vault only in data_json format.
If I use input_type as "yaml" or "json" and try to store it to the Vault, It will not be stored in the format alertmanager wants the file to be. To workaround this issue, I can make the config file as txt file and then encode it using `input_type = raw` and it works, but the issue is maintainability of the code in long term. I can't differentiate between file versions for comparison.
But If we merge this change, It will be a neat way of managing my usecase, I can still encode the file in `yaml` (and manage the file efficiently) and upload it to vault as `raw` (so that alertManager can mount it as yaml)

Thanks @nhuray for taking up this change.

**Comment by waddles** [comment]
+1

My use case is to store a [YAML snippet for Users](https://coreos.com/os/docs/2303.3.0/clc-examples.html#users-and-groups) (encrypting the password hashes) which is converted by the [config transpiler](https://github.com/poseidon/terraform-provider-ct) as part of [Typhoon](https://github.com/poseidon/typhoon)

The problem is, I need to provide the YAML snippet as a string to the Typhoon module.

I don't understand why the YAML needs to be flattened to a map of `dotted.keys` to values in the first place. Wouldn't it be easier to just call [yamldecode()](https://www.terraform.io/docs/configuration/functions/yamldecode.html) on the decrypted yaml file contents?

**Comment by carlpett** [comment]
Thank you all for your patience and detailing your use-cases! Merging this, finally :smiley: 

@waddles Regarding why the dotted keys, it is to a large extent a historical artifact. In TF 0.11, there wasn't a `yamldecode`, and setting the data output like this had the effect of turning into a nested map. This was apparently unintentional in TF-core, however, and stopped working in 0.12. So in some sense, with modern versions of TF 0.12, (`yamldecode` was added in 0.12.2), you could just always go with raw output and handle it in TF config directly. 
"Soon"(:tm:) the Terraform SDK will allow providers to output richer data structures again

**Pull request merged**
