### PR TITLE
Added AWS SSO generated credentials support by using newer aws-sdk ve…

### PR DESCRIPTION
**Pull request by leszek-niewiadomski**
…rsion.

https://github.com/aws/aws-sdk-go/pull/3761

### CODE REVIEW

**Comment by carlpett** [comment]
Hi @leszek-niewiadomski,
Thanks for the PR! Could you get this merged into the main [mozilla/sops](github.com/mozilla/sops) repo first, then we can bump the sops version instead?

**Comment by DavidJacob** [comment]
@carlpett I got a PR to support this merged into SOPS today. https://github.com/mozilla/sops/pull/823

**Comment by carlpett** [comment]
Nice work! Hopefully there's a new release of sops soon then, so we can upgrade here.

**Comment by carlpett** [comment]
I've updated to the new sops release in #63. This is available in v0.6.1!

**Pull request closed without merging**
