### PR TITLE
upgrade sops to v3.7.3

### PR DESCRIPTION
**Pull request by multani**
[sops v3.7.3](https://github.com/mozilla/sops/releases/tag/v3.7.3) was released yesterday :)

It should help for https://github.com/carlpett/terraform-provider-sops/issues/83, looking forward to it!

### CODE REVIEW

**Comment by carlpett** [comment]
Thanks! Especially for the work pushing forward on the sops side :)
I'll check why the tests are failing.

**Comment by carlpett** [comment]
I'm unfortunately coming up with nothing. I'll try to get some more time tomorrow, but also cannot replicate locally. I've been putting of migrating to Actions for CI, maybe this will be the thing that pushes it over the edge...

**Comment by multani** [comment]
I can give you a hand if you are interested in a migration to GitHub Action 👍

**Comment by carlpett** [comment]
That would be much appreciated! :heart: I've got a rather busy week at work, so might take a while until I can get it done otherwise

**Comment by multani** [comment]
Tests are running :)

**Comment by carlpett** [comment]
Thanks, let's see how the first release goes :)

**Comment by multani** [comment]
> Thanks, let's see how the first release goes :)

Looks like it went smoothly! :)

Thanks for the merge and the release!

**Comment by multani** [comment]
I'll give it a try, but I think there's a bunch of authentication-related issues that could actually be closed with this new release, I'll comment in them directly :)

**Comment by carlpett** [comment]
Oops, and I also need to sign the binaries. Coming up.

**Pull request merged**
